// Generated by CoffeeScript 1.12.7
(function() {
  var cubes, list, math, num, number, opposite, race, square,
    slice = [].slice;

  number = 42;

  opposite = true;

  console.log(number);

  console.log(opposite);

  if (opposite) {
    number = -42;
  }

  console.log(number);

  square = function(x) {
    return x * x;
  };

  console.log(square(number));

  list = [1, 2, 3, 4, 5];

  console.log(list);

  math = {
    root: Math.sqrt,
    square: square,
    cube: function(x) {
      return x * square(x);
    }
  };

  race = function() {
    var runners, winner;
    winner = arguments[0], runners = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    return print(winner, runners);
  };

  cubes = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = list.length; i < len; i++) {
      num = list[i];
      results.push(math.cube(num));
    }
    return results;
  })();

  console.log(cubes);

}).call(this);
